import math
raceStrMod=0
raceDexMod=0
raceConMod=0
raceIntMod=0
raceWisMod=0
raceChaMod=0
lvl=1
xp=0
charaName=' '
hitDice='undefined'
profBonus=2
inputStr=10
inputDex=10
inputCon=10
inputInt=10
inputWis=10
inputCha=10
cha=inputCha+raceChaMod
wis=inputWis+raceWisMod
tempHp=0
blinded = 'false'
charmed = 'false'
deafened = 'false'
frightened = 'false'
grappled = 'false'
incapacitated = 'false'
invisible = 'false'
paralyzed = 'false'
petrified = 'false'
poisoned = 'false'
prone = 'false'
restrained = 'false'
stunned = 'false'
unconscious = 'false'
intel=inputInt+raceIntMod
con=inputCon+raceConMod
dex=inputDex+raceDexMod
stre=inputStr+raceStrMod
strMod=math.floor((stre-10)/2)
dexMod=math.floor((dex-10)/2)
conMod=math.floor((con-10)/2)
intMod=math.floor((intel-10)/2)
wisMod=math.floor((wis-10)/2)
chaMod=math.floor((cha-10)/2)
hp=conMod
armourClass=10+dexMod
acro = dexMod
anim = wisMod
arca = intMod 
athl = strMod
dece = chaMod
hist = intMod
insi = wisMod
inti = chaMod
inve = intMod
medi = wisMod
natu = intMod
perc = wisMod
perf = chaMod
pers = chaMod
reli = intMod
slei = dexMod
stea = dexMod
surv = wisMod
lvlType = 'undefined'
exhaust = 0
passivePerc = 10 + wisMod
passiveInve = 10 + intMod
passiveInsi = 10 + wisMod
walkSpeed = 30
username = 'username'
password = 'password'
inputUser = ' '
inputPass = ' '
loginCompleted = False
background = 'undefined'
armourProf = ' '
weaponProf = ' '
toolsProf = ' '
languages = ' '
lvl1 = 'false'
diceType = 'd6'
roll = 0
rollMod = 0
subrace = 'undefined'
strProf=False
dexProf=False
intProf=False
conProf=False
wisProf=False
chaProf=False
num1=0
num2=0
