# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notes.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import init


class Ui_notes(object):
    def infoSheet(self):
        from infoSheet import Ui_infoSheet
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_infoSheet()
        self.ui.setupUi(self.window2)
        self.window2.show()
    def notes(self):
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_notes()
        self.ui.setupUi(self.window2)
        self.window2.show()
    '''def saves(self):
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_saves()
        self.ui.setupUi(self.window2)
        self.window2.show()'''
    def charaSheet(self):
        from charaSheet import Ui_charaSheet
        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_charaSheet()
        self.ui.setupUi(self.window2)
        self.window2.show()
    def setupUi(self, notes):
        notes.setObjectName("notes")
        notes.resize(1180, 431)
        self.centralwidget = QtWidgets.QWidget(notes)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 81, 371))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.toSheet = QtWidgets.QPushButton(self.groupBox)
        self.toSheet.setGeometry(QtCore.QRect(10, 10, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.toSheet.setFont(font)
        self.toSheet.setObjectName("toSheet")
        self.toSheet.clicked.connect(self.charaSheet)
        self.toSheet.clicked.connect(notes.close)
        self.toInfo = QtWidgets.QPushButton(self.groupBox)
        self.toInfo.setGeometry(QtCore.QRect(10, 100, 61, 61))
        self.toInfo.clicked.connect(self.infoSheet)
        self.toInfo.clicked.connect(notes.close)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.toInfo.setFont(font)
        self.toInfo.setObjectName("toInfo")
        self.doNothing3 = QtWidgets.QPushButton(self.groupBox)
        self.doNothing3.setGeometry(QtCore.QRect(10, 190, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.doNothing3.setFont(font)
        self.doNothing3.setObjectName("doNothing3")
        self.toSaves = QtWidgets.QPushButton(self.groupBox)
        self.toSaves.setGeometry(QtCore.QRect(10, 280, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.toSaves.setFont(font)
        self.toSaves.setObjectName("toSaves")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(100, 50, 500, 350))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 10, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(650, 50, 500, 350))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(820, 10, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 10, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        notes.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(notes)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 861, 18))
        self.menubar.setObjectName("menubar")
        notes.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(notes)
        self.statusbar.setObjectName("statusbar")
        notes.setStatusBar(self.statusbar)

        self.loadNotes()
        self.pushButton.clicked.connect(self.saveNotes)
        self.retranslateUi(notes)
        QtCore.QMetaObject.connectSlotsByName(notes)

    def retranslateUi(self, notes):
        _translate = QtCore.QCoreApplication.translate
        notes.setWindowTitle(_translate("notes", "Notes"))
        self.toSheet.setText(_translate("notes", "👤"))
        self.toInfo.setText(_translate("notes", "ⓘ"))
        self.doNothing3.setText(_translate("notes", "📖"))
        self.toSaves.setText(_translate("notes", "💾"))
        self.label.setText(_translate("notes", "Game Notes"))
        self.label_2.setText(_translate("notes", "Character Notes"))
        self.pushButton.setText(_translate("notes", "Save Notes"))

    def saveNotes(self):
        init.gameNotes = self.plainTextEdit.toPlainText()
        init.charaNotes = self.plainTextEdit_2.toPlainText()
    
    def loadNotes(self):
        self.plainTextEdit.setPlainText(f'{init.gameNotes}')
        self.plainTextEdit_2.setPlainText(f'{init.charaNotes}')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    notes = QtWidgets.QMainWindow()
    ui = Ui_notes()
    ui.setupUi(notes)
    notes.show()
    sys.exit(app.exec_())
